import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const peyda = localFont({
  src: [
    {
      path: "./fonts/Peyda-ExtraBold.ttf",
      weight: "bold",
      style: "normal",
    },
    {
      path: "./fonts/Peyda-Bold.ttf",
      weight: "bold",
      style: "normal",
    },
    {
      path: "./fonts/peyda-extralight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/peyda-light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Peyda-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/Peyda-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Peyda-Regular.ttf",
      weight: "normal",
      style: "normal",
    },
    {
      path: "./fonts/Peyda-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Peyda-Thin.ttf",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-peyda",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${peyda.className} antialiased bg-white-200 dark:bg-primary-900 transition-colors duration-300 container 2xl:max-w-[2000px] mx-auto overflow-x-hidden`}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
